#!/usr/bin/env bash
set -euo pipefail
# =============================================================================
# Multi-Git — Setup Command
# Generates SSH keys, SSH config, allowed_signers, per-account git configs
# =============================================================================

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"
load_accounts
ensure_ssh_dir

MARKER_START="# >>> multi-git-setup >>>"
MARKER_END="# <<< multi-git-setup <<<"

# ---- Generate or move SSH keys (one per account) ----------------------------
generate_keys() {
  info "Checking SSH keys..."
  for account in "${ACCOUNTS[@]}"; do
    IFS='|' read -r label email host user <<< "$account"
    key_file="$SSH_DIR/id_ed25519_${label}"

    if [[ -f "$key_file" ]]; then
      ok "Key already exists: $key_file"
      continue
    fi

    # Check if there's an existing default key matching this email
    # (e.g. ~/.ssh/id_ed25519 or ~/.ssh/id_rsa) that we can adopt
    local moved=false
    for candidate in "$SSH_DIR"/id_ed25519 "$SSH_DIR"/id_rsa "$SSH_DIR"/id_ecdsa; do
      if [[ -f "$candidate" && -f "${candidate}.pub" ]]; then
        # Check if the key comment matches this account's email
        if grep -q "$email" "${candidate}.pub" 2>/dev/null; then
          info "Found existing key matching '$email': $candidate"
          echo -n "  Move to $key_file? [y/N] "
          read -r answer
          if [[ "$answer" =~ ^[Yy]$ ]]; then
            mv "$candidate" "$key_file"
            mv "${candidate}.pub" "${key_file}.pub"
            ok "Moved: $candidate -> $key_file"
            moved=true
            break
          fi
        fi
      fi
    done

    if [[ "$moved" == false ]]; then
      info "Generating new key for [$label] ($email)..."
      ssh-keygen -t ed25519 -C "$email" -f "$key_file" -N ""
      ok "Generated: $key_file"
    fi
  done
}

# ---- Write SSH config -------------------------------------------------------
write_ssh_config() {
  local config_file="$SSH_DIR/config"

  if [[ -f "$config_file" ]]; then
    sed -i.bak "/$MARKER_START/,/$MARKER_END/d" "$config_file"
    rm -f "${config_file}.bak"
  fi

  info "Writing SSH config..."

  {
    echo ""
    echo "$MARKER_START"
    echo "# Auto-generated by multi-git — do not edit this block manually"
    echo ""

    for account in "${ACCOUNTS[@]}"; do
      IFS='|' read -r label email host user <<< "$account"
      key_file="$SSH_DIR/id_ed25519_${label}"

      cat <<EOF
# ${label} account (${email})
Host ${host}-${label}
  HostName ${host}
  User git
  IdentityFile ${key_file}
  IdentitiesOnly yes

EOF
    done

    echo "$MARKER_END"
  } >> "$config_file"

  chmod 600 "$config_file"
  ok "SSH config updated: $config_file"
}

# ---- Create allowed_signers -------------------------------------------------
write_allowed_signers() {
  local signers_file="$SSH_DIR/allowed_signers"

  if [[ -f "$signers_file" ]]; then
    sed -i.bak "/$MARKER_START/,/$MARKER_END/d" "$signers_file"
    rm -f "${signers_file}.bak"
  fi

  info "Writing allowed_signers..."

  {
    echo "$MARKER_START"
    for account in "${ACCOUNTS[@]}"; do
      IFS='|' read -r label email host user <<< "$account"
      key_file="$SSH_DIR/id_ed25519_${label}.pub"
      pub_key=$(cat "$key_file")
      echo "$email $pub_key"
    done
    echo "$MARKER_END"
  } >> "$signers_file"

  chmod 644 "$signers_file"
  ok "Allowed signers: $signers_file"
}

# ---- Generate per-account .gitconfig includes -------------------------------
write_git_configs() {
  info "Writing per-account Git configs..."

  for account in "${ACCOUNTS[@]}"; do
    IFS='|' read -r label email host user <<< "$account"
    key_file="$SSH_DIR/id_ed25519_${label}"
    git_config="$HOME/.gitconfig-${label}"

    cat > "$git_config" <<EOF
[user]
  email = ${email}
  name = ${user}
  signingkey = ${key_file}.pub

[gpg]
  format = ssh

[gpg "ssh"]
  allowedSignersFile = ${SSH_DIR}/allowed_signers

[commit]
  gpgsign = true

[tag]
  gpgsign = true
EOF

    ok "Git config: $git_config"
  done
}

# ---- Post-setup instructions ------------------------------------------------
print_instructions() {
  echo ""
  echo -e "${GREEN}=========================================${NC}"
  echo -e "${GREEN}  Setup Complete!${NC}"
  echo -e "${GREEN}=========================================${NC}"
  echo ""

  echo -e "${CYAN}STEP 1: Add SSH public keys to your Git host${NC}"
  echo "  Upload each key to GitHub -> Settings -> SSH and GPG keys -> New SSH key"
  echo ""
  for account in "${ACCOUNTS[@]}"; do
    IFS='|' read -r label email host user <<< "$account"
    echo -e "  ${YELLOW}[$label]${NC} ($email):"
    echo "  Auth key  -> Add as 'Authentication Key'"
    echo "  Sign key  -> Add as 'Signing Key' (same key, different type!)"
    echo ""
    echo "  Public key:"
    echo -e "  ${GREEN}$(cat "$SSH_DIR/id_ed25519_${label}.pub")${NC}"
    echo ""
  done

  echo -e "${CYAN}STEP 2: Configure repos${NC}"
  echo ""
  echo "  Option A — Per-repo (recommended):"
  echo "    ./multi-git.sh repo <label>"
  echo ""
  echo "  Option B — Directory-based auto-include in ~/.gitconfig:"
  echo ""
  for account in "${ACCOUNTS[@]}"; do
    IFS='|' read -r label email host user <<< "$account"
    echo "    [includeIf \"gitdir:~/projects/${label}/\"]"
    echo "      path = ~/.gitconfig-${label}"
    echo ""
  done

  echo -e "${CYAN}STEP 3: Update remote URLs to use SSH host aliases${NC}"
  echo ""
  for account in "${ACCOUNTS[@]}"; do
    IFS='|' read -r label email host user <<< "$account"
    echo "  ${label}: git remote set-url origin git@${host}-${label}:${user}/repo.git"
  done
  echo ""

  echo -e "${CYAN}STEP 4: Test SSH connections${NC}"
  echo "  ./multi-git.sh test"
  echo ""

  echo -e "${CYAN}STEP 5: Verify commits are signed${NC}"
  echo "  git log --show-signature -1"
  echo "  git verify-commit HEAD"
  echo ""
}

# ---- Run --------------------------------------------------------------------
generate_keys
write_ssh_config
write_allowed_signers
write_git_configs
print_instructions
